version: '3.9'

services:
  api:
    environment:
      ENVIRONMENT: production
    restart: always

  frontend:
    restart: always

  postgres:
    restart: always

  notification-service:
    restart: always
