// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type BuildingTypeEnum string

const (
	BuildingTypeEnumResidential BuildingTypeEnum = "Residential"
	BuildingTypeEnumCommercial  BuildingTypeEnum = "Commercial"
	BuildingTypeEnumMixed       BuildingTypeEnum = "Mixed"
)

func (e *BuildingTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildingTypeEnum(s)
	case string:
		*e = BuildingTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildingTypeEnum: %T", src)
	}
	return nil
}

type NullBuildingTypeEnum struct {
	BuildingTypeEnum BuildingTypeEnum `json:"building_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if BuildingTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildingTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.BuildingTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildingTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildingTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildingTypeEnum), nil
}

type Building struct {
	ID               int32                 `db:"id" json:"id"`
	PropertyID       int32                 `db:"property_id" json:"property_id"`
	BuildingName     string                `db:"building_name" json:"building_name"`
	BuildingCode     string                `db:"building_code" json:"building_code"`
	BuildingType     BuildingTypeEnum      `db:"building_type" json:"building_type"`
	TotalFloors      sql.NullInt32         `db:"total_floors" json:"total_floors"`
	HasElevator      sql.NullBool          `db:"has_elevator" json:"has_elevator"`
	ConstructionYear sql.NullInt32         `db:"construction_year" json:"construction_year"`
	Metadata         pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	ActiveStatus     sql.NullBool          `db:"active_status" json:"active_status"`
	OrganizationID   int32                 `db:"organization_id" json:"organization_id"`
	CreatedAt        sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime          `db:"updated_at" json:"updated_at"`
}

type Lease struct {
	ID              int32          `db:"id" json:"id"`
	UnitID          int32          `db:"unit_id" json:"unit_id"`
	TenantID        int32          `db:"tenant_id" json:"tenant_id"`
	LeaseType       string         `db:"lease_type" json:"lease_type"`
	StartDate       time.Time      `db:"start_date" json:"start_date"`
	EndDate         sql.NullTime   `db:"end_date" json:"end_date"`
	DurationMonths  int32          `db:"duration_months" json:"duration_months"`
	MonthlyRent     float64        `db:"monthly_rent" json:"monthly_rent"`
	SecurityDeposit sql.NullString `db:"security_deposit" json:"security_deposit"`
	Active          sql.NullBool   `db:"active" json:"active"`
	OrganizationID  int32          `db:"organization_id" json:"organization_id"`
	CreatedAt       sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Organization struct {
	ID               int32         `db:"id" json:"id"`
	Name             string        `db:"name" json:"name"`
	Slug             string        `db:"slug" json:"slug"`
	SubscriptionTier string        `db:"subscription_tier" json:"subscription_tier"`
	MaxUsers         sql.NullInt32 `db:"max_users" json:"max_users"`
	Active           sql.NullBool  `db:"active" json:"active"`
	CreatedAt        sql.NullTime  `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime  `db:"updated_at" json:"updated_at"`
}

type Payment struct {
	ID             int32          `db:"id" json:"id"`
	UnitID         int32          `db:"unit_id" json:"unit_id"`
	TenantID       int32          `db:"tenant_id" json:"tenant_id"`
	BuildingID     int32          `db:"building_id" json:"building_id"`
	PropertyID     int32          `db:"property_id" json:"property_id"`
	OrganizationID int32          `db:"organization_id" json:"organization_id"`
	Month          int32          `db:"month" json:"month"`
	Year           int32          `db:"year" json:"year"`
	AmountDue      float64        `db:"amount_due" json:"amount_due"`
	AmountPaid     sql.NullString `db:"amount_paid" json:"amount_paid"`
	Status         sql.NullString `db:"status" json:"status"`
	PaymentMethod  sql.NullString `db:"payment_method" json:"payment_method"`
	PaymentDate    sql.NullTime   `db:"payment_date" json:"payment_date"`
	Notes          sql.NullString `db:"notes" json:"notes"`
	ReceiptNumber  sql.NullString `db:"receipt_number" json:"receipt_number"`
	DueDate        sql.NullTime   `db:"due_date" json:"due_date"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Property struct {
	ID             int32                 `db:"id" json:"id"`
	PropertyName   string                `db:"property_name" json:"property_name"`
	PropertyCode   string                `db:"property_code" json:"property_code"`
	Address        string                `db:"address" json:"address"`
	City           sql.NullString        `db:"city" json:"city"`
	PostalCode     sql.NullString        `db:"postal_code" json:"postal_code"`
	PropertyType   string                `db:"property_type" json:"property_type"`
	TotalBuildings sql.NullInt32         `db:"total_buildings" json:"total_buildings"`
	Metadata       pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	Active         sql.NullBool          `db:"active" json:"active"`
	OrganizationID int32                 `db:"organization_id" json:"organization_id"`
	CreatedAt      sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime          `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	ID             int32          `db:"id" json:"id"`
	Name           string         `db:"name" json:"name"`
	TenantType     string         `db:"tenant_type" json:"tenant_type"`
	PhoneNumber    sql.NullString `db:"phone_number" json:"phone_number"`
	Email          sql.NullString `db:"email" json:"email"`
	NidNumber      sql.NullString `db:"nid_number" json:"nid_number"`
	Address        sql.NullString `db:"address" json:"address"`
	Active         sql.NullBool   `db:"active" json:"active"`
	OrganizationID int32          `db:"organization_id" json:"organization_id"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Unit struct {
	ID             int32                 `db:"id" json:"id"`
	BuildingID     int32                 `db:"building_id" json:"building_id"`
	PropertyID     int32                 `db:"property_id" json:"property_id"`
	UnitNumber     string                `db:"unit_number" json:"unit_number"`
	UnitName       sql.NullString        `db:"unit_name" json:"unit_name"`
	Floor          sql.NullInt32         `db:"floor" json:"floor"`
	Section        sql.NullString        `db:"section" json:"section"`
	UnitType       string                `db:"unit_type" json:"unit_type"`
	MonthlyRent    float64               `db:"monthly_rent" json:"monthly_rent"`
	Metadata       pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	Active         sql.NullBool          `db:"active" json:"active"`
	OrganizationID int32                 `db:"organization_id" json:"organization_id"`
	CreatedAt      sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime          `db:"updated_at" json:"updated_at"`
}
