// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countBuildingPaymentsInPeriod = `-- name: CountBuildingPaymentsInPeriod :one
SELECT COUNT(*)
FROM payments p
LEFT JOIN units u ON p.unit_id = u.id
LEFT JOIN tenants t ON p.tenant_id = t.id
LEFT JOIN buildings b ON p.building_id = b.id
LEFT JOIN properties pr ON p.property_id = pr.id
WHERE p.building_id = $1
  AND p.created_at >= $2
  AND p.created_at <= $3
`

type CountBuildingPaymentsInPeriodParams struct {
	BuildingID  int32        `db:"building_id" json:"building_id"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	CreatedAt_2 sql.NullTime `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) CountBuildingPaymentsInPeriod(ctx context.Context, arg CountBuildingPaymentsInPeriodParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBuildingPaymentsInPeriod, arg.BuildingID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (
    unit_id, tenant_id, building_id, property_id, organization_id,
    month, year, amount_due, amount_paid, status,
    payment_method, payment_date, receipt_number, notes, due_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
RETURNING id, unit_id, tenant_id, building_id, property_id, organization_id,
    month, year, amount_due, amount_paid, status,
    COALESCE(payment_method, '') AS payment_method,
    COALESCE(notes, '') AS notes,
    COALESCE(receipt_number, '') AS receipt_number,
    payment_date, due_date, created_at, updated_at
`

type CreatePaymentParams struct {
	UnitID         int32          `db:"unit_id" json:"unit_id"`
	TenantID       int32          `db:"tenant_id" json:"tenant_id"`
	BuildingID     int32          `db:"building_id" json:"building_id"`
	PropertyID     int32          `db:"property_id" json:"property_id"`
	OrganizationID int32          `db:"organization_id" json:"organization_id"`
	Month          int32          `db:"month" json:"month"`
	Year           int32          `db:"year" json:"year"`
	AmountDue      float64        `db:"amount_due" json:"amount_due"`
	AmountPaid     float64        `db:"amount_paid" json:"amount_paid"`
	Status         string         `db:"status" json:"status"`
	PaymentMethod  sql.NullString `db:"payment_method" json:"payment_method"`
	PaymentDate    sql.NullTime   `db:"payment_date" json:"payment_date"`
	ReceiptNumber  sql.NullString `db:"receipt_number" json:"receipt_number"`
	Notes          sql.NullString `db:"notes" json:"notes"`
	DueDate        sql.NullTime   `db:"due_date" json:"due_date"`
}

type CreatePaymentRow struct {
	ID             int32          `db:"id" json:"id"`
	UnitID         int32          `db:"unit_id" json:"unit_id"`
	TenantID       int32          `db:"tenant_id" json:"tenant_id"`
	BuildingID     int32          `db:"building_id" json:"building_id"`
	PropertyID     int32          `db:"property_id" json:"property_id"`
	OrganizationID int32          `db:"organization_id" json:"organization_id"`
	Month          int32          `db:"month" json:"month"`
	Year           int32          `db:"year" json:"year"`
	AmountDue      float64        `db:"amount_due" json:"amount_due"`
	AmountPaid     sql.NullString `db:"amount_paid" json:"amount_paid"`
	Status         sql.NullString `db:"status" json:"status"`
	PaymentMethod  string         `db:"payment_method" json:"payment_method"`
	Notes          string         `db:"notes" json:"notes"`
	ReceiptNumber  string         `db:"receipt_number" json:"receipt_number"`
	PaymentDate    sql.NullTime   `db:"payment_date" json:"payment_date"`
	DueDate        sql.NullTime   `db:"due_date" json:"due_date"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
}

// Queries for payment repository
// All payment-related queries for sqlc generation
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.UnitID,
		arg.TenantID,
		arg.BuildingID,
		arg.PropertyID,
		arg.OrganizationID,
		arg.Month,
		arg.Year,
		arg.AmountDue,
		arg.AmountPaid,
		arg.Status,
		arg.PaymentMethod,
		arg.PaymentDate,
		arg.ReceiptNumber,
		arg.Notes,
		arg.DueDate,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.TenantID,
		&i.BuildingID,
		&i.PropertyID,
		&i.OrganizationID,
		&i.Month,
		&i.Year,
		&i.AmountDue,
		&i.AmountPaid,
		&i.Status,
		&i.PaymentMethod,
		&i.Notes,
		&i.ReceiptNumber,
		&i.PaymentDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuildingLevelSummary = `-- name: GetBuildingLevelSummary :one
SELECT
    COUNT(DISTINCT building_id) AS total_buildings,
    COALESCE(SUM(amount_due), 0) AS total_due,
    COALESCE(SUM(amount_paid), 0) AS total_paid
FROM payments
`

type GetBuildingLevelSummaryRow struct {
	TotalBuildings int64       `db:"total_buildings" json:"total_buildings"`
	TotalDue       interface{} `db:"total_due" json:"total_due"`
	TotalPaid      interface{} `db:"total_paid" json:"total_paid"`
}

func (q *Queries) GetBuildingLevelSummary(ctx context.Context) (GetBuildingLevelSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getBuildingLevelSummary)
	var i GetBuildingLevelSummaryRow
	err := row.Scan(&i.TotalBuildings, &i.TotalDue, &i.TotalPaid)
	return i, err
}

const getBuildingPaymentAnalytics = `-- name: GetBuildingPaymentAnalytics :one
SELECT
    COALESCE(SUM(amount_paid), 0) AS total_revenue,
    CASE WHEN COALESCE(SUM(amount_due), 0) > 0
        THEN (COALESCE(SUM(amount_paid), 0) / COALESCE(SUM(amount_due), 0)) * 100
        ELSE 0 END AS collection_rate,
    COALESCE(AVG(
        CASE WHEN payment_date IS NOT NULL AND due_date IS NOT NULL
            THEN EXTRACT(EPOCH FROM (payment_date - due_date)) / 86400
            ELSE NULL END
    ), 0) AS avg_payment_days,
    COUNT(CASE WHEN status='Overdue' THEN 1 END) AS overdue_count
FROM payments
WHERE building_id = $1 AND created_at >= $2 AND created_at <= $3
`

type GetBuildingPaymentAnalyticsParams struct {
	BuildingID  int32        `db:"building_id" json:"building_id"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	CreatedAt_2 sql.NullTime `db:"created_at_2" json:"created_at_2"`
}

type GetBuildingPaymentAnalyticsRow struct {
	TotalRevenue   interface{} `db:"total_revenue" json:"total_revenue"`
	CollectionRate int32       `db:"collection_rate" json:"collection_rate"`
	AvgPaymentDays interface{} `db:"avg_payment_days" json:"avg_payment_days"`
	OverdueCount   int64       `db:"overdue_count" json:"overdue_count"`
}

func (q *Queries) GetBuildingPaymentAnalytics(ctx context.Context, arg GetBuildingPaymentAnalyticsParams) (GetBuildingPaymentAnalyticsRow, error) {
	row := q.db.QueryRowContext(ctx, getBuildingPaymentAnalytics, arg.BuildingID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetBuildingPaymentAnalyticsRow
	err := row.Scan(
		&i.TotalRevenue,
		&i.CollectionRate,
		&i.AvgPaymentDays,
		&i.OverdueCount,
	)
	return i, err
}

const getBuildingPaymentStats = `-- name: GetBuildingPaymentStats :one
SELECT
    COUNT(*) AS total_records,
    COALESCE(SUM(amount_due), 0) AS total_due,
    COALESCE(SUM(amount_paid), 0) AS total_paid,
    COALESCE(SUM(CASE WHEN status='Overdue' THEN amount_due - amount_paid ELSE 0 END), 0) AS total_overdue,
    COUNT(CASE WHEN status='Paid' THEN 1 END) AS paid_count,
    COUNT(CASE WHEN status='Due' THEN 1 END) AS due_count,
    COUNT(CASE WHEN status='Partial' THEN 1 END) AS partial_count,
    COUNT(CASE WHEN status='Overdue' THEN 1 END) AS overdue_count
FROM payments
WHERE building_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type GetBuildingPaymentStatsParams struct {
	BuildingID  int32        `db:"building_id" json:"building_id"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	CreatedAt_2 sql.NullTime `db:"created_at_2" json:"created_at_2"`
}

type GetBuildingPaymentStatsRow struct {
	TotalRecords int64       `db:"total_records" json:"total_records"`
	TotalDue     interface{} `db:"total_due" json:"total_due"`
	TotalPaid    interface{} `db:"total_paid" json:"total_paid"`
	TotalOverdue interface{} `db:"total_overdue" json:"total_overdue"`
	PaidCount    int64       `db:"paid_count" json:"paid_count"`
	DueCount     int64       `db:"due_count" json:"due_count"`
	PartialCount int64       `db:"partial_count" json:"partial_count"`
	OverdueCount int64       `db:"overdue_count" json:"overdue_count"`
}

func (q *Queries) GetBuildingPaymentStats(ctx context.Context, arg GetBuildingPaymentStatsParams) (GetBuildingPaymentStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getBuildingPaymentStats, arg.BuildingID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetBuildingPaymentStatsRow
	err := row.Scan(
		&i.TotalRecords,
		&i.TotalDue,
		&i.TotalPaid,
		&i.TotalOverdue,
		&i.PaidCount,
		&i.DueCount,
		&i.PartialCount,
		&i.OverdueCount,
	)
	return i, err
}

const getBuildingPaymentTrend = `-- name: GetBuildingPaymentTrend :many
SELECT year, month,
    COALESCE(SUM(amount_due), 0) AS due,
    COALESCE(SUM(amount_paid), 0) AS paid
FROM payments
WHERE building_id = $1 AND created_at >= $2 AND created_at <= $3
GROUP BY year, month
ORDER BY year, month
`

type GetBuildingPaymentTrendParams struct {
	BuildingID  int32        `db:"building_id" json:"building_id"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	CreatedAt_2 sql.NullTime `db:"created_at_2" json:"created_at_2"`
}

type GetBuildingPaymentTrendRow struct {
	Year  int32       `db:"year" json:"year"`
	Month int32       `db:"month" json:"month"`
	Due   interface{} `db:"due" json:"due"`
	Paid  interface{} `db:"paid" json:"paid"`
}

func (q *Queries) GetBuildingPaymentTrend(ctx context.Context, arg GetBuildingPaymentTrendParams) ([]GetBuildingPaymentTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, getBuildingPaymentTrend, arg.BuildingID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildingPaymentTrendRow{}
	for rows.Next() {
		var i GetBuildingPaymentTrendRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Due,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuildingPaymentsInPeriod = `-- name: GetBuildingPaymentsInPeriod :many
SELECT
    p.id, p.unit_id, p.tenant_id, p.building_id, p.property_id, p.organization_id,
    p.month, p.year, p.amount_due, p.amount_paid, p.status,
    COALESCE(p.payment_method, '') AS payment_method,
    COALESCE(p.notes, '') AS notes,
    COALESCE(p.receipt_number, '') AS receipt_number,
    p.payment_date, p.due_date, p.created_at, p.updated_at,
    COALESCE(pr.property_name, '') AS property_name,
    COALESCE(b.building_name, '') AS building_name,
    COALESCE(b.building_code, '') AS building_code,
    COALESCE(u.unit_number, '') AS unit_number,
    COALESCE(u.unit_type::text, '') AS unit_type,
    COALESCE(t.name, '') AS tenant_name
FROM payments p
LEFT JOIN units u ON p.unit_id = u.id
LEFT JOIN tenants t ON p.tenant_id = t.id
LEFT JOIN buildings b ON p.building_id = b.id
LEFT JOIN properties pr ON p.property_id = pr.id
WHERE p.building_id = $1
  AND p.created_at >= $2
  AND p.created_at <= $3
ORDER BY p.year DESC, p.month DESC
LIMIT $4 OFFSET $5
`

type GetBuildingPaymentsInPeriodParams struct {
	BuildingID  int32        `db:"building_id" json:"building_id"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	CreatedAt_2 sql.NullTime `db:"created_at_2" json:"created_at_2"`
	Limit       int32        `db:"limit" json:"limit"`
	Offset      int32        `db:"offset" json:"offset"`
}

type GetBuildingPaymentsInPeriodRow struct {
	ID             int32          `db:"id" json:"id"`
	UnitID         int32          `db:"unit_id" json:"unit_id"`
	TenantID       int32          `db:"tenant_id" json:"tenant_id"`
	BuildingID     int32          `db:"building_id" json:"building_id"`
	PropertyID     int32          `db:"property_id" json:"property_id"`
	OrganizationID int32          `db:"organization_id" json:"organization_id"`
	Month          int32          `db:"month" json:"month"`
	Year           int32          `db:"year" json:"year"`
	AmountDue      float64        `db:"amount_due" json:"amount_due"`
	AmountPaid     sql.NullString `db:"amount_paid" json:"amount_paid"`
	Status         sql.NullString `db:"status" json:"status"`
	PaymentMethod  string         `db:"payment_method" json:"payment_method"`
	Notes          string         `db:"notes" json:"notes"`
	ReceiptNumber  string         `db:"receipt_number" json:"receipt_number"`
	PaymentDate    sql.NullTime   `db:"payment_date" json:"payment_date"`
	DueDate        sql.NullTime   `db:"due_date" json:"due_date"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
	PropertyName   string         `db:"property_name" json:"property_name"`
	BuildingName   string         `db:"building_name" json:"building_name"`
	BuildingCode   string         `db:"building_code" json:"building_code"`
	UnitNumber     string         `db:"unit_number" json:"unit_number"`
	UnitType       interface{}    `db:"unit_type" json:"unit_type"`
	TenantName     string         `db:"tenant_name" json:"tenant_name"`
}

func (q *Queries) GetBuildingPaymentsInPeriod(ctx context.Context, arg GetBuildingPaymentsInPeriodParams) ([]GetBuildingPaymentsInPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, getBuildingPaymentsInPeriod,
		arg.BuildingID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildingPaymentsInPeriodRow{}
	for rows.Next() {
		var i GetBuildingPaymentsInPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.TenantID,
			&i.BuildingID,
			&i.PropertyID,
			&i.OrganizationID,
			&i.Month,
			&i.Year,
			&i.AmountDue,
			&i.AmountPaid,
			&i.Status,
			&i.PaymentMethod,
			&i.Notes,
			&i.ReceiptNumber,
			&i.PaymentDate,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PropertyName,
			&i.BuildingName,
			&i.BuildingCode,
			&i.UnitNumber,
			&i.UnitType,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT
    COALESCE(SUM(amount_due), 0) AS total_due,
    COALESCE(SUM(amount_paid), 0) AS total_paid,
    COALESCE(SUM(CASE WHEN status != 'Paid' THEN amount_due - amount_paid ELSE 0 END), 0) AS total_pending,
    COALESCE(SUM(CASE WHEN status='Overdue' THEN amount_due - amount_paid ELSE 0 END), 0) AS total_overdue,
    (SELECT COUNT(DISTINCT id) FROM properties) AS property_count,
    (SELECT COUNT(DISTINCT id) FROM buildings) AS building_count,
    (SELECT COUNT(DISTINCT id) FROM units WHERE active = true) AS unit_count,
    (SELECT COUNT(DISTINCT id) FROM tenants WHERE active = true) AS tenant_count
FROM payments
`

type GetDashboardSummaryRow struct {
	TotalDue      interface{} `db:"total_due" json:"total_due"`
	TotalPaid     interface{} `db:"total_paid" json:"total_paid"`
	TotalPending  interface{} `db:"total_pending" json:"total_pending"`
	TotalOverdue  interface{} `db:"total_overdue" json:"total_overdue"`
	PropertyCount int64       `db:"property_count" json:"property_count"`
	BuildingCount int64       `db:"building_count" json:"building_count"`
	UnitCount     int64       `db:"unit_count" json:"unit_count"`
	TenantCount   int64       `db:"tenant_count" json:"tenant_count"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardSummary)
	var i GetDashboardSummaryRow
	err := row.Scan(
		&i.TotalDue,
		&i.TotalPaid,
		&i.TotalPending,
		&i.TotalOverdue,
		&i.PropertyCount,
		&i.BuildingCount,
		&i.UnitCount,
		&i.TenantCount,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, unit_id, tenant_id, building_id, property_id, organization_id,
    month, year, amount_due, amount_paid, status,
    COALESCE(payment_method, '') AS payment_method,
    COALESCE(notes, '') AS notes,
    COALESCE(receipt_number, '') AS receipt_number,
    payment_date, due_date, created_at, updated_at
FROM payments
WHERE id = $1
`

type GetPaymentByIDRow struct {
	ID             int32          `db:"id" json:"id"`
	UnitID         int32          `db:"unit_id" json:"unit_id"`
	TenantID       int32          `db:"tenant_id" json:"tenant_id"`
	BuildingID     int32          `db:"building_id" json:"building_id"`
	PropertyID     int32          `db:"property_id" json:"property_id"`
	OrganizationID int32          `db:"organization_id" json:"organization_id"`
	Month          int32          `db:"month" json:"month"`
	Year           int32          `db:"year" json:"year"`
	AmountDue      float64        `db:"amount_due" json:"amount_due"`
	AmountPaid     sql.NullString `db:"amount_paid" json:"amount_paid"`
	Status         sql.NullString `db:"status" json:"status"`
	PaymentMethod  string         `db:"payment_method" json:"payment_method"`
	Notes          string         `db:"notes" json:"notes"`
	ReceiptNumber  string         `db:"receipt_number" json:"receipt_number"`
	PaymentDate    sql.NullTime   `db:"payment_date" json:"payment_date"`
	DueDate        sql.NullTime   `db:"due_date" json:"due_date"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, id int32) (GetPaymentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.TenantID,
		&i.BuildingID,
		&i.PropertyID,
		&i.OrganizationID,
		&i.Month,
		&i.Year,
		&i.AmountDue,
		&i.AmountPaid,
		&i.Status,
		&i.PaymentMethod,
		&i.Notes,
		&i.ReceiptNumber,
		&i.PaymentDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIDWithDetails = `-- name: GetPaymentByIDWithDetails :one
SELECT
    p.id, p.unit_id, p.tenant_id, p.building_id, p.property_id, p.organization_id,
    p.month, p.year, p.amount_due, p.amount_paid, p.status,
    COALESCE(p.payment_method, '') AS payment_method,
    COALESCE(p.notes, '') AS notes,
    COALESCE(p.receipt_number, '') AS receipt_number,
    p.payment_date, p.due_date, p.created_at, p.updated_at,
    COALESCE(pr.property_name, '') AS property_name,
    COALESCE(b.building_name, '') AS building_name,
    COALESCE(b.building_code, '') AS building_code,
    COALESCE(u.unit_number, '') AS unit_number,
    COALESCE(u.unit_type::text, '') AS unit_type,
    COALESCE(t.name, '') AS tenant_name
FROM payments p
LEFT JOIN units u ON p.unit_id = u.id
LEFT JOIN tenants t ON p.tenant_id = t.id
LEFT JOIN buildings b ON p.building_id = b.id
LEFT JOIN properties pr ON p.property_id = pr.id
WHERE p.id = $1
`

type GetPaymentByIDWithDetailsRow struct {
	ID             int32          `db:"id" json:"id"`
	UnitID         int32          `db:"unit_id" json:"unit_id"`
	TenantID       int32          `db:"tenant_id" json:"tenant_id"`
	BuildingID     int32          `db:"building_id" json:"building_id"`
	PropertyID     int32          `db:"property_id" json:"property_id"`
	OrganizationID int32          `db:"organization_id" json:"organization_id"`
	Month          int32          `db:"month" json:"month"`
	Year           int32          `db:"year" json:"year"`
	AmountDue      float64        `db:"amount_due" json:"amount_due"`
	AmountPaid     sql.NullString `db:"amount_paid" json:"amount_paid"`
	Status         sql.NullString `db:"status" json:"status"`
	PaymentMethod  string         `db:"payment_method" json:"payment_method"`
	Notes          string         `db:"notes" json:"notes"`
	ReceiptNumber  string         `db:"receipt_number" json:"receipt_number"`
	PaymentDate    sql.NullTime   `db:"payment_date" json:"payment_date"`
	DueDate        sql.NullTime   `db:"due_date" json:"due_date"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
	PropertyName   string         `db:"property_name" json:"property_name"`
	BuildingName   string         `db:"building_name" json:"building_name"`
	BuildingCode   string         `db:"building_code" json:"building_code"`
	UnitNumber     string         `db:"unit_number" json:"unit_number"`
	UnitType       interface{}    `db:"unit_type" json:"unit_type"`
	TenantName     string         `db:"tenant_name" json:"tenant_name"`
}

func (q *Queries) GetPaymentByIDWithDetails(ctx context.Context, id int32) (GetPaymentByIDWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIDWithDetails, id)
	var i GetPaymentByIDWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.TenantID,
		&i.BuildingID,
		&i.PropertyID,
		&i.OrganizationID,
		&i.Month,
		&i.Year,
		&i.AmountDue,
		&i.AmountPaid,
		&i.Status,
		&i.PaymentMethod,
		&i.Notes,
		&i.ReceiptNumber,
		&i.PaymentDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PropertyName,
		&i.BuildingName,
		&i.BuildingCode,
		&i.UnitNumber,
		&i.UnitType,
		&i.TenantName,
	)
	return i, err
}

const getPropertyPaymentStats = `-- name: GetPropertyPaymentStats :one
SELECT
    COUNT(*) AS total_records,
    COALESCE(SUM(amount_due), 0) AS total_due,
    COALESCE(SUM(amount_paid), 0) AS total_paid,
    COALESCE(SUM(CASE WHEN status='Overdue' THEN amount_due - amount_paid ELSE 0 END), 0) AS total_overdue,
    COUNT(CASE WHEN status='Paid' THEN 1 END) AS paid_count,
    COUNT(CASE WHEN status='Due' THEN 1 END) AS due_count,
    COUNT(CASE WHEN status='Partial' THEN 1 END) AS partial_count,
    COUNT(CASE WHEN status='Overdue' THEN 1 END) AS overdue_count
FROM payments
WHERE property_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type GetPropertyPaymentStatsParams struct {
	PropertyID  int32        `db:"property_id" json:"property_id"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	CreatedAt_2 sql.NullTime `db:"created_at_2" json:"created_at_2"`
}

type GetPropertyPaymentStatsRow struct {
	TotalRecords int64       `db:"total_records" json:"total_records"`
	TotalDue     interface{} `db:"total_due" json:"total_due"`
	TotalPaid    interface{} `db:"total_paid" json:"total_paid"`
	TotalOverdue interface{} `db:"total_overdue" json:"total_overdue"`
	PaidCount    int64       `db:"paid_count" json:"paid_count"`
	DueCount     int64       `db:"due_count" json:"due_count"`
	PartialCount int64       `db:"partial_count" json:"partial_count"`
	OverdueCount int64       `db:"overdue_count" json:"overdue_count"`
}

func (q *Queries) GetPropertyPaymentStats(ctx context.Context, arg GetPropertyPaymentStatsParams) (GetPropertyPaymentStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPropertyPaymentStats, arg.PropertyID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetPropertyPaymentStatsRow
	err := row.Scan(
		&i.TotalRecords,
		&i.TotalDue,
		&i.TotalPaid,
		&i.TotalOverdue,
		&i.PaidCount,
		&i.DueCount,
		&i.PartialCount,
		&i.OverdueCount,
	)
	return i, err
}

const getSystemPaymentStats = `-- name: GetSystemPaymentStats :one
SELECT
    COUNT(*) AS total_records,
    COALESCE(SUM(amount_due), 0) AS total_due,
    COALESCE(SUM(amount_paid), 0) AS total_paid,
    COALESCE(SUM(CASE WHEN status='Overdue' THEN amount_due - amount_paid ELSE 0 END), 0) AS total_overdue,
    COUNT(CASE WHEN status='Paid' THEN 1 END) AS paid_count,
    COUNT(CASE WHEN status='Due' THEN 1 END) AS due_count,
    COUNT(CASE WHEN status='Partial' THEN 1 END) AS partial_count,
    COUNT(CASE WHEN status='Overdue' THEN 1 END) AS overdue_count
FROM payments
WHERE created_at >= $1
  AND created_at <= $2
`

type GetSystemPaymentStatsParams struct {
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	CreatedAt_2 sql.NullTime `db:"created_at_2" json:"created_at_2"`
}

type GetSystemPaymentStatsRow struct {
	TotalRecords int64       `db:"total_records" json:"total_records"`
	TotalDue     interface{} `db:"total_due" json:"total_due"`
	TotalPaid    interface{} `db:"total_paid" json:"total_paid"`
	TotalOverdue interface{} `db:"total_overdue" json:"total_overdue"`
	PaidCount    int64       `db:"paid_count" json:"paid_count"`
	DueCount     int64       `db:"due_count" json:"due_count"`
	PartialCount int64       `db:"partial_count" json:"partial_count"`
	OverdueCount int64       `db:"overdue_count" json:"overdue_count"`
}

func (q *Queries) GetSystemPaymentStats(ctx context.Context, arg GetSystemPaymentStatsParams) (GetSystemPaymentStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSystemPaymentStats, arg.CreatedAt, arg.CreatedAt_2)
	var i GetSystemPaymentStatsRow
	err := row.Scan(
		&i.TotalRecords,
		&i.TotalDue,
		&i.TotalPaid,
		&i.TotalOverdue,
		&i.PaidCount,
		&i.DueCount,
		&i.PartialCount,
		&i.OverdueCount,
	)
	return i, err
}

const searchLeases = `-- name: SearchLeases :many
SELECT
    l.id AS lease_id,
    t.id AS tenant_id,
    t.name AS tenant_name,
    COALESCE(t.phone_number, '') AS tenant_phone,
    p.id AS property_id,
    p.property_name,
    b.id AS building_id,
    b.building_name,
    b.building_code,
    u.id AS unit_id,
    u.unit_number,
    COALESCE(u.unit_type::text, '') AS unit_type,
    l.start_date AS lease_start_date,
    l.end_date AS lease_end_date,
    l.monthly_rent,
    l.active
FROM leases l
LEFT JOIN tenants t ON l.tenant_id = t.id
LEFT JOIN units u ON l.unit_id = u.id
LEFT JOIN buildings b ON u.building_id = b.id
LEFT JOIN properties p ON u.property_id = p.id
WHERE l.organization_id = $1
    AND l.active = true
    AND (
        LOWER(t.name) LIKE $2
        OR LOWER(p.property_name) LIKE $2
        OR LOWER(b.building_name) LIKE $2
        OR LOWER(b.building_code) LIKE $2
        OR LOWER(u.unit_number) LIKE $2
        OR (CASE WHEN t.phone_number IS NOT NULL THEN LOWER(t.phone_number) ELSE '' END) LIKE $2
        OR CAST(l.id AS TEXT) LIKE $2
    )
ORDER BY t.name, l.start_date DESC
LIMIT 50
`

type SearchLeasesParams struct {
	OrganizationID int32  `db:"organization_id" json:"organization_id"`
	Name           string `db:"name" json:"name"`
}

type SearchLeasesRow struct {
	LeaseID        int32          `db:"lease_id" json:"lease_id"`
	TenantID       sql.NullInt32  `db:"tenant_id" json:"tenant_id"`
	TenantName     sql.NullString `db:"tenant_name" json:"tenant_name"`
	TenantPhone    string         `db:"tenant_phone" json:"tenant_phone"`
	PropertyID     sql.NullInt32  `db:"property_id" json:"property_id"`
	PropertyName   sql.NullString `db:"property_name" json:"property_name"`
	BuildingID     sql.NullInt32  `db:"building_id" json:"building_id"`
	BuildingName   sql.NullString `db:"building_name" json:"building_name"`
	BuildingCode   sql.NullString `db:"building_code" json:"building_code"`
	UnitID         sql.NullInt32  `db:"unit_id" json:"unit_id"`
	UnitNumber     sql.NullString `db:"unit_number" json:"unit_number"`
	UnitType       interface{}    `db:"unit_type" json:"unit_type"`
	LeaseStartDate time.Time      `db:"lease_start_date" json:"lease_start_date"`
	LeaseEndDate   sql.NullTime   `db:"lease_end_date" json:"lease_end_date"`
	MonthlyRent    float64        `db:"monthly_rent" json:"monthly_rent"`
	Active         sql.NullBool   `db:"active" json:"active"`
}

func (q *Queries) SearchLeases(ctx context.Context, arg SearchLeasesParams) ([]SearchLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchLeases, arg.OrganizationID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchLeasesRow{}
	for rows.Next() {
		var i SearchLeasesRow
		if err := rows.Scan(
			&i.LeaseID,
			&i.TenantID,
			&i.TenantName,
			&i.TenantPhone,
			&i.PropertyID,
			&i.PropertyName,
			&i.BuildingID,
			&i.BuildingName,
			&i.BuildingCode,
			&i.UnitID,
			&i.UnitNumber,
			&i.UnitType,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.MonthlyRent,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
